# Generated by Django 5.0 on 2023-12-19 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narx')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='summa')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
