# Generated by Django 5.0 on 2023-12-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price'),
        ),
        migrations.CreateModel(
            name='Remains',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='price')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='summa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
